"""Initial migration

Revision ID: a0fa97334f63
Revises: 
Create Date: 2024-10-16 23:01:20.953940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0fa97334f63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet_breed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_breed',
    sa.Column('pet_id', sa.INTEGER(), nullable=False),
    sa.Column('breed_id', sa.INTEGER(), nullable=False),
    sa.Column('is_primary_breed', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['breed_id'], ['breeds.id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('pet_id', 'breed_id')
    )
    # ### end Alembic commands ###
